import type { TokensFile } from "./types";

export const TOKENS_START = "/* figma-tokens:start — generated by /figma-sync, do not edit by hand */";
export const TOKENS_END = "/* figma-tokens:end */";

export function tokensToCssBlock(t: TokensFile): string {
  const names = Object.keys(t).sort();
  const lightDecls = names.map((n) => `  --${n}: ${t[n].$value};`).join("\n");
  const darkDecls = names
    .map((n) => {
      const dark = t[n].$extensions.mode.dark;
      if (dark === null || dark === undefined || dark === "") {
        throw new Error(`Token "${n}" is missing its dark-mode value`);
      }
      return `  --${n}: ${dark};`;
    })
    .join("\n");
  return [
    TOKENS_START,
    `:root,\nhtml[data-theme="light"] {\n${lightDecls}\n}`,
    `html[data-theme="dark"] {\n${darkDecls}\n}`,
    TOKENS_END,
  ].join("\n");
}

export function spliceTokensIntoCss(css: string, block: string): string {
  const start = css.indexOf(TOKENS_START);
  const end = css.indexOf(TOKENS_END);
  if (start === -1 && end === -1) {
    return block + "\n\n" + css;
  }
  if (start !== -1 && end !== -1 && end > start) {
    return css.slice(0, start) + block + css.slice(end + TOKENS_END.length);
  }
  throw new Error(
    "Malformed figma-tokens markers in CSS: expected both start and end markers in order, or neither."
  );
}

export function parseCssBlock(css: string): Record<string, { light: string; dark: string }> {
  const start = css.indexOf(TOKENS_START);
  const end = css.indexOf(TOKENS_END);
  if (start === -1 || end === -1 || end < start) return {};
  const region = css.slice(start, end);
  const darkIdx = region.indexOf('data-theme="dark"');
  const lightPart = darkIdx === -1 ? region : region.slice(0, darkIdx);
  const darkPart = darkIdx === -1 ? "" : region.slice(darkIdx);
  const grab = (part: string): Record<string, string> => {
    const map: Record<string, string> = {};
    const re = /--([\w-]+):\s*([^;]+);/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(part)) !== null) map[m[1]] = m[2].trim();
    return map;
  };
  const light = grab(lightPart);
  const dark = grab(darkPart);
  const out: Record<string, { light: string; dark: string }> = {};
  for (const name of new Set([...Object.keys(light), ...Object.keys(dark)])) {
    out[name] = { light: light[name] ?? "", dark: dark[name] ?? "" };
  }
  return out;
}
