import type { EntityDiff } from "./diff";
import type { ComponentsFile, TokensFile } from "./types";

export function renderDesignMd(args: {
  tokens: TokensFile;
  components: ComponentsFile;
  diffs: EntityDiff[];
  lastSync: string;
}): string {
  const { tokens, components, diffs, lastSync } = args;

  const tokenRows = Object.keys(tokens)
    .sort()
    .map((n) => `| \`--${n}\` | ${tokens[n].$value} | ${tokens[n].$extensions.mode.dark} | \`${tokens[n].$extensions.css}\` |`)
    .join("\n");

  const compRows = Object.keys(components)
    .sort()
    .map((n) => {
      const c = components[n];
      const variants = Object.entries(c.variants).map(([k, v]) => `${k}: ${v.join("/")}`).join("; ") || "—";
      return `| ${n} | \`${c.figmaKey}\` | ${c.source ?? "**unmapped**"} | ${variants} |`;
    })
    .join("\n");

  const drift = diffs.filter((d) => d.status !== "in-sync");
  const driftSection = drift.length
    ? drift.map((d) => `- \`${d.key}\` — **${d.status}**`).join("\n")
    : "In sync — no drift.";

  return [
    "# Design System",
    "",
    "> **GENERATED by `/figma-sync` — DO NOT EDIT by hand.** Source of truth is Figma.",
    `> Last sync: ${lastSync}`,
    "",
    "## Tokens",
    "",
    "| Token | Light | Dark | CSS |",
    "| --- | --- | --- | --- |",
    tokenRows,
    "",
    "## Components",
    "",
    "| Name | Figma key | Source | Variants |",
    "| --- | --- | --- | --- |",
    compRows,
    "",
    "## Drift / Actions",
    "",
    driftSection,
    "",
  ].join("\n");
}
